In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8, 8, 4], [7, 9, 5], [6, 10, 6], [5, 12, 7]], columns = ['cgpa', 'profile_score', 'lpa'])

In [3]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [10]:
model = Sequential()

# Architecture = Input dimension is 2 hidden layer 1 with two nodes and a output node

model.add(Dense(2, activation = 'linear', input_dim = 2))
model.add(Dense(1, activation = 'linear'))

In [11]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
# Keras initialize the weights randomly

model.get_weights()

[array([[ 1.0890745 , -0.7795313 ],
        [-0.69911194,  1.0671774 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.06206405],
        [-0.8087073 ]], dtype=float32),
 array([0.], dtype=float32)]

In [17]:
new_weights = [np.array([[0.1, 0.1],
                         [0.1, 0.1]], dtype = np.float32),
               np.array([0., 0.], dtype = np.float32),
               np.array([[0.1],
                         [0.1]], dtype = np.float32),
               np.array([0.], dtype = np.float32)]

In [19]:
model.set_weights(new_weights)

In [22]:
# We changed the random weights and biases to make our model similar that we made using simple python

model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [23]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = 'mean_squared_error', optimizer = optimizer)

In [26]:
model.fit(df.iloc[:, 0:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 25.4431 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 27.1752
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 28.8977
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 33.1260 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26.1926 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.7757
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 27.4432 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 30.9645
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25.3418
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 21.3688
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 23.8750
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 21.5754
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 20.1966
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 28.1715
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.3733
Epoch 16/75
4/4

In [27]:
model.get_weights()

[array([[0.3734759 , 0.3734759 ],
        [0.36554345, 0.36554345]], dtype=float32),
 array([0.27218682, 0.27218682], dtype=float32),
 array([[0.372803],
        [0.372803]], dtype=float32),
 array([0.20468488], dtype=float32)]